"""add tables

Revision ID: 21cab29667ba
Revises: 
Create Date: 2024-04-02 16:44:14.270347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cab29667ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('goals', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_table('workout_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('focus_area', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_programs'))
    )
    op.create_table('client_workout_programs',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('workout_program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_workout_programs_client_id_clients')),
    sa.ForeignKeyConstraint(['workout_program_id'], ['workout_programs.id'], name=op.f('fk_client_workout_programs_workout_program_id_workout_programs')),
    sa.PrimaryKeyConstraint('client_id', 'workout_program_id', name=op.f('pk_client_workout_programs'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('workout_program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_sessions_client_id_clients')),
    sa.ForeignKeyConstraint(['workout_program_id'], ['workout_programs.id'], name=op.f('fk_sessions_workout_program_id_workout_programs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('client_workout_programs')
    op.drop_table('workout_programs')
    op.drop_table('clients')
    # ### end Alembic commands ###
