"""delete difficulty column

Revision ID: f8fc272b7b8e
Revises: c83409f1f524
Create Date: 2024-03-30 19:54:30.961651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fc272b7b8e'
down_revision = 'c83409f1f524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_programs', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
